# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

Class XieCheng():
    def setup_method(self,method)
        ChromeDriver = "D:\\chromedriver.exe"
        self.driver = webdriver.Chrome(ChromeDriver)
        self.vars = {}



        driver.get("https://www.baidu.com")
