# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestTestpyjingyoutestpyjingyou():
    def setup_method(self, method):
        ChromeDriver = "D:\\chromedriver.exe"
        self.driver = webdriver.Chrome(ChromeDriver)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    # def wait_for_window(self, timeout=2):
    #     time.sleep(round(timeout / 1000))
    #     wh_now = self.driver.window_handles
    #     wh_then = self.vars["window_handles"]
    #     if len(wh_now) > len(wh_then):
    #         return set(wh_now).difference(set(wh_then)).pop()

    def test_testpyjingyoutestpyjingyou(self):
        self.driver.get("https://www.ctrip.com/")
        time.sleep(8)
        list1 = self.driver.find_elements_by_tag_name("input")
        print(list1)
        self.driver.find_element_by_xpath("// b[contains(., '火车')]").click()
        '''self.driver.find_element(By.CSS_SELECTOR, ".s_tab_nocurrent:nth-child(6) > b").click()'''
        time.sleep(2)
        self.driver.maximize_window()
        time.sleep(2)
        self.driver.find_element(By.ID, "notice01").send_keys("北京")
        time.sleep(2)
        self.driver.find_element(By.ID, "DdateObj").send_keys("2020-09-19")
        time.sleep(2)
        self.driver.find_element(By.ID, "notice02").send_keys("合肥")
        time.sleep(2)
        self.driver.find_element(By.ID, "searchTicket").click()
        time.sleep(2)
        try:
            self.driver.find_element_by_css_selector("div[trainname='G261']").find_element_by_class_name(
                "qp_btn2").click()
        except Exception as err:
            print("输入日期不能大于当天" + err)
        # self.driver.find_element_by_class_name("w6")(By.CSS_SELECTOR,".railway_list:nth-child(2) div:nth-child(1) > .qp_btn2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".input-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".input-name").send_keys("葛士祺")
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > .input-card").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > .input-card").send_keys("341224199409045311")
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) > .input-card").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) > .input-card").send_keys("15643583292")
        self.driver.find_element(By.LINK_TEXT, "添加成人").click()
        self.driver.execute_script("window.scrollTo(0,392)")
        self.driver.find_element(By.CSS_SELECTOR, ".pasg-add:nth-child(2) a").click()
        self.driver.find_element(By.ID, "contact-mobile").click()
        self.driver.find_element(By.ID, "contact-mobile").send_keys("15643583292")
        self.driver.find_element(By.CSS_SELECTOR, "#invoiceVue label").click()
        self.driver.find_element(By.CSS_SELECTOR, "#invoiceVue label").click()

if __name__ == "__main__":
    pytest.main()
